#!/bin/bash

docker stop portainer-agent
docker rm portainer-agent
docker rmi portainer/agent:latest

docker run -d -p 9001:9001 --name portainer-agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:latest
