#!/bin/bash

# Auhtor: Julian Lamprecht
# V1.0

# Script to run bash in a container

if [ $# -ne 1 ]; then
    >&2 echo "Not enough arguments"
    echo "Usage: $(basename "$0") [Container]"
    exit 1
fi

CONTAINER_NAME=$1

docker exec -it $CONTAINER_NAME /bin/bash
