#!/bin/bash

if [ $# -ne 2 ]; then
    >&2 echo "Not enough arguments"
    echo "Usage: $(basename "$0") [.tar archive path] [volume]"
    exit 1
fi

ARCHIVE_PATH=$1
VOLUME_NAME=$2

docker run --rm -v $VOLUME_NAME:/data -v $ARCHIVE_PATH:/archive/backup.tar alpine:latest ash -c "tar -xvf /archive/backup.tar -C /"
