#!/bin/bash

VOLUME_NAME_OLD=$1
VOLUME_NAME_NEW=$2

docker volume create $2

#Copies the content of the old volume to the newly created volume
docker run --rm -v $1:/from -v $2:/to alpine:latest cp -a /from/. /to